
allow-lan: false
bind-address: '*'
dns:
  default-nameserver:
  - 223.5.5.5
  - 119.29.29.29
  enable: true
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  fallback:
  - tls://1.0.0.1:853
  - https://cloudflare-dns.com/dns-query
  - https://dns.google/dns-query
  fallback-filter:
    geoip: true
    ipcidr:
    - 240.0.0.0/4
    - 0.0.0.0/32
  ipv6: false
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  use-hosts: true
external-controller: 127.0.0.1:1123
ipv6: false
log-level: info
mixed-port: 1122
mode: rule
proxies: 
- {name: test-node, server: example.com, port: 444, type: vmess, uuid: 9d2924b7-936b-32dd-83fa-9a8601510972, alterId: 1, cipher: auto, tls: false, skip-cert-verify: false, network: ws, ws-opts: {path: /, headers: {Host: bf419d5f59f96a.windowsupdate.com}}, ws-path: /, ws-headers: {Host: bf419d5f59f96a.windowsupdate.com}}
proxy-groups:
- name: auto
  type: select
  proxies: 
   - test-node

rules:
- DOMAIN-SUFFIX,google.com,auto
- DOMAIN-KEYWORD,google,auto
- DOMAIN,google.com,auto
- SRC-IP-CIDR,192.168.1.201/32,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- DST-PORT,80,DIRECT
- SRC-PORT,7777,DIRECT
- MATCH,auto
